version: '3.8'

services:
  majorsystem-backend:
    image: ghcr.io/theupsider/majorsystem-backend:latest
    container_name: majorsystem-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      - ./data:/usr/src/app/prisma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
